backsite/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import *

app_name='backsite'
urlpatterns = [
    path('',dashboard,name='dashboard'),
    path('login/',loginPage,name='loginpage'),
    path('logout/',logoutPage,name='logoutpage'),
    path('blogs/',blog,name='blogs'),
    path('create-blog/',create_blog,name='create_blog'),
    path('update-blog/<int:id>',create_blog,name='update_blog'),
    path('delete-blog/<int:id>',delete_blog,name='delete_blog'),
    path('create_update_about/',create_update_about,name='create_about'),
    path('create_update_about/<int:id>',create_update_about,name='update_about'),
    path('settings/',settings_func,name='settings_func'),
    path('cat_type_ajax/',create_update_cat_type_ajax,name='cat_type_ajax'),
    path('del_cat_type_ajax/',del_cat_type_ajax,name='del_cat_type_ajax'),
    path('edit_cat_type_ajax/',edit_cat_type_ajax,name='edit_cat_type_ajax'),
    path('my_cats/',my_cats,name='my_cats'),
    path('create_cat/',create_cat,name='create_cat'),
    path('update_cat/<int:id>',create_cat,name='update_cat'),
    path('delete_cat/<int:id>',delete_cat,name='delete_cat'),

]

cattery/urls.py
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from frontsite.views import index,about,contact_func,cats_blog,cat_info
from core.views import error_404_view
from django.conf.urls import (
handler400, handler403, handler404, handler500
)

urlpatterns = [
    path('',index,name='index'),
    path('about/',about,name='about'),
    path('contact_us/',contact_func,name='contact_us'),
    path('valerian_admin/',include('backsite.urls',namespace='panel')),
    path('blog/',include('frontsite.urls',namespace='front')),
    path('our_cats/',cats_blog,name='cats_blog'),
    path('our_cats/<int:id>',cat_info,name='cat_info'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

handler404 = 'core.views.error_404_view'
handler500 = 'core.views.error_500_view'

frontsite/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import *

app_name='frontsite'
urlpatterns = [
    path('',blogs,name='blogs'),
    path('<str:slug>/',blog_page,name='blog_page'),


]

backsite/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.



class Blog(models.Model):
    title=models.CharField(verbose_name='Başlık',max_length=255)
    content = RichTextField(verbose_name='İçerik')
    url=models.CharField(verbose_name='Url',max_length=999)
    created_at=models.DateTimeField(auto_now_add=True)
    is_active=models.BooleanField(verbose_name='Aktif',default=False)
    is_mainpage = models.BooleanField(verbose_name='Ana Sayfa',default=False)
    img = models.FileField(upload_to='img/')

    def __str__(self):
        return self.title


class CatsType(models.Model):
    title=models.CharField(verbose_name='Kedi Türü',max_length=255)


    def __str__(self):
        return self.title

class Cats(models.Model):
    DISI= 1
    ERKEK = 2

    GENDER_CHOICES = (
        (1, 'Dişi'),
        (2, 'Erkek'),
    )
    gender = models.IntegerField(choices=GENDER_CHOICES)
    title=models.CharField(verbose_name='Başlık',max_length=255)
    cat_type=models.ForeignKey(CatsType,on_delete=models.CASCADE)
    content = RichTextField(verbose_name='Hakkında')
    created_at=models.DateTimeField(auto_now_add=True)
    img = models.FileField(upload_to='img/')
    is_active=models.BooleanField(verbose_name='Aktif',default=False)
    is_mainpage = models.BooleanField(verbose_name='Ana Sayfa',default=False)

    def __str__(self):
        return self.title

backsite/forms.py
from django import forms
from ckeditor.widgets import CKEditorWidget
from .models import Blog,Cats,CatsType


qs = CatsType.objects.all().values_list('id','title') if CatsType.objects.all().exists() else (0,'Bir kedi seçin')

class BlogForm(forms.ModelForm):

    class Meta:
        model = Blog
        fields = ('title', 'content','url','img','is_active','is_mainpage')
        widgets = {
            'title': forms.TextInput(attrs={'placeholder': u'Başlık','class':'form-control'}),
            'content': CKEditorWidget(),
            'url': forms.TextInput(attrs={'placeholder': u'Url','class':'form-control'}),

        }

class CatForm(forms.ModelForm):

    class Meta:
        model = Cats
        fields = ('title', 'content','gender','cat_type','img','is_active','is_mainpage')

        widgets = {
            'title': forms.TextInput(attrs={'placeholder': u'Başlık','class':'form-control'}),
            'content': CKEditorWidget(),
            'cat_type':forms.Select(choices=qs,attrs={'class':'form-control'}),
            'gender':forms.Select(attrs={'class':'form-control'}),

        }

backsite/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth import login,authenticate,logout
from core.decorators import is_panel,is_login
from .forms import BlogForm,CatForm
from .models import Blog,CatsType,Cats
from core.models import About
from core.views import is_ajax
from core.forms import AboutForm
from django.http import JsonResponse
from django.urls import reverse




def authenticate_user(email, password):
    try:
        user = User.objects.get(email=email)
    except User.DoesNotExist:
        return None
    else:
        if user.check_password(password):
            return user

    return None


def loginPage(request):
    if is_ajax and request.method=='POST':
        email = request.POST.get('email')
        passwd = request.POST.get('password')
        user = authenticate_user(email=email,password=passwd)
        if user is None:
            result = {'success':False}
            return JsonResponse(result)
        else:
            login(request,user)
            path=reverse('backsite:dashboard')
            result = {'success':True,'path':path}
            return JsonResponse(result)
    else:
        if request.user.is_authenticated:
            return redirect('backsite:dashboard')
        else:
            return render(request,'backsite/login.html')

@is_login
def logoutPage(request):
    logout(request)
    return redirect('backsite:loginpage')

@is_login
def dashboard(request):
    active_blogs=Blog.objects.filter(is_active=1).count()
    active_cats=Cats.objects.filter(is_active=1).count()
    total_blogs=Blog.objects.all().count()
    total_cats=Cats.objects.all().count()
    context={
        'active_cats':active_cats,
        'active_blogs':active_blogs,
        'total_blogs':total_blogs,
        'total_cats':total_cats,
    }
    return render(request,'backsite/index.html',context)
# Create your views here.

# Create your views here.

@is_login
def blog(request):
    blogs=Blog.objects.all()
    context={
    'blogs':blogs
    }
    return render(request,'backsite/blog.html',context)

@is_login
def create_blog(request,id=None):
    if id:
        blog = get_object_or_404(Blog,id=id)
        form=BlogForm(request.POST or None,request.FILES or None,instance=blog)
    else:
        form=BlogForm(request.POST or None,request.FILES or None)
    if form.is_valid():
        form.save()
        return redirect('backsite:blogs')
    context={
        'form':form
    }
    return render(request,'backsite/create-blog.html',context)

@is_login
def delete_blog(request,id):
    blog = get_object_or_404(Blog,id=id)
    blog.delete()
    return redirect('backsite:blogs')

@is_login
def create_update_about(request,id=None):
    if id:
        about = get_object_or_404(About,id=id)
        form=AboutForm(request.POST or None,instance=about)
    else:
        form=AboutForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('backsite:settings_func')
    context={
        'form':form
    }
    return render(request,'backsite/create_about.html',context)

@is_login
def settings_func(request):
    about=About.objects.first()
    cat_types=CatsType.objects.all()
    context={'about':about,'cat_types':cat_types}
    return render(request,'backsite/settings.html',context)

@is_login
def create_update_cat_type_ajax(request,id=None):
    if is_ajax:
        if request.method == 'POST':
            id=request.POST.get('cat_type_id')
            cat_type=request.POST.get('cat_type')
            if id:
                catType=CatsType.objects.get(id=id)
                catType.title=cat_type
                catType.save()
                data={'msg':'İşlem Başarılı','success':True}
                return JsonResponse(data)
            else:
                if not CatsType.objects.filter(title=cat_type).exists():
                    obj=CatsType.objects.create(title=cat_type)
                    data={'msg':'İşlem Başarılı','success':True}
                else:
                    data={'msg':'Kedi türü daha önce eklenmiş','success':False}
                return JsonResponse(data)


@is_login
def del_cat_type_ajax(request):
    if is_ajax:
        if request.method == 'GET':
            id=request.GET.get('id')
            if CatsType.objects.filter(id=id).exists():
                CatsType.objects.get(id=id).delete()
                data={'msg':'İşlem Başarılı','success':True}
            else:
                data={'msg':'Tür Silinemiyor','success':False}
            return JsonResponse(data)

@is_login
def edit_cat_type_ajax(request):
    if is_ajax:
        if request.method == 'GET':
            id=request.GET.get('id')
            if CatsType.objects.filter(id=id).exists():
                types=CatsType.objects.get(id=id)
                data={'title':types.title,'id':types.id,'success':True}
            else:
                data={'msg':'Bir hata oluştu','success':False}
            return JsonResponse(data)

@is_login
def my_cats(request):
    cats = Cats.objects.all().order_by('-created_at')
    return render(request,'backsite/my_cats.html',{'cats':cats})

@is_login
def create_cat(request,id=None):
    if id:
        cat = get_object_or_404(Cats,id=id)
        form=CatForm(request.POST or None,request.FILES or None,instance=cat)
    else:
        form=CatForm(request.POST or None,request.FILES or None)
    if form.is_valid():
        form.save()
        return redirect('backsite:my_cats')
    else:
        print(form.errors)
    context={
        'form':form
    }
    return render(request,'backsite/create-cat.html',context)

@is_login
def delete_cat(request,id):
    cat = get_object_or_404(Cats,id=id)
    cat.delete()
    return redirect('backsite:my_cats')

backsite/templates/backsite/blog.html
{% extends 'backsite/main.html' %}
{% load static %}


{% block body %}
<div class="container-fluid p-0">

        <h1 class="h3 mb-3">Blog Kontrol Sayfası <a href="{% url 'backsite:create_blog' %}" class="btn btn-primary btn-lg" style="float:right">Blog Ekle</a></h1>
  <div class="row">
      {% for blog in blogs %}
      <div class="col-12 col-md-3">
            <div class="card">
              <img class="card-img-top" src="{{blog.img.url}}" style="max-width: 44%;margin: 0 auto;">
              <div class="card-header">
                <h5 class="card-title mb-0">{{blog.title}}</h5>
              </div>
              <div class="card-body">
                <p class="card-text">{{blog.content|safe|truncatechars:11}}</p>
                <a href="{% url 'frontsite:blog_page' slug=blog.url %}" target="_blank" class="btn btn-primary"><i style="vertical-align: text-top!important;" data-feather="arrow-right"></i> Makaleye Git</a>
                <a href="{% url 'backsite:update_blog' id=blog.id %}" class="btn btn-success"><i style="vertical-align: text-top!important;" data-feather="edit"></i> Düzenle</a>
                <a href="{% url 'backsite:delete_blog' id=blog.id %}" class="btn btn-danger"><i style="vertical-align: text-top!important;" data-feather="delete"></i> Sil</a>
              </div>
            </div>
          </div>

      {% endfor %}

  </div>

</div>
{% endblock %}

backsite/templates/backsite/create-blog.html
{% extends 'backsite/main.html' %}
{% load static %}
{% block js%}
<script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
<script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
{% endblock %}


{% block body %}
<div class="container-fluid p-0">
  <div class='row'>
    <div class="col-md-8">
      <form method="post" enctype="multipart/form-data" >
        {% csrf_token %}
        <div class="card">
                  <div class="card-header">
                    <h5 class="card-title mb-0">{{form.title.label}}</h5>
                  </div>
                  <div class="card-body">
                    {{form.title}}
                  </div>
                  <div class="card-header">
                    <h5 class="card-title mb-0">{{form.content.label}}</h5>
                  </div>
                  <div class="card-body">
                    {{form.content}}
                  </div>
                  <div class="card-header">
                    <h5 class="card-title mb-0">{{form.url.label}}</h5>
                  </div>
                  <div class="card-body">
                    {{form.url}}
                  </div>
                  <div class="card-header">
                    <h5 class="card-title mb-0">Başlık Resmi</h5>
                  </div>
                  <div class="card-body">
                    {{form.img}}
                  </div>
                  <div class="card-header">
                    <h5 class="card-title mb-0">{{form.is_active.label}}</h5>
                  </div>
                  <div class="card-body">
                    {{form.is_active}}
                  </div>
                  <div class="card-header">
                    <h5 class="card-title mb-0">{{form.is_mainpage.label}}</h5>
                  </div>
                  <div class="card-body">
                    {{form.is_mainpage}}
                  </div>
                </div>
                <button type='submit' class="btn btn-primary btn-lg">Kaydet</button>

      </form>
    </div>


  </div>
</div>

{% endblock %}

backsite/templates/backsite/create-cat.html
{% extends 'backsite/main.html' %}
{% load static %}
{% block js%}
<script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
<script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
{% endblock %}


{% block body %}
<div class="container-fluid p-0">
  <div class='row'>
    <div class="col-md-8">
      <form method="post" enctype="multipart/form-data" >
        {% csrf_token %}
        <div class="card">
          {% for field in form %}
                  <div class="card-header">
                    <h5 class="card-title mb-0">
                      {% if field.label == 'Gender' %}
                      Cinsiyet
                      {% elif filed.label == 'Img' %}
                      Kedi Resmi
                      {% elif field.label == 'Cat type' %}
                      Kedi Türü
                      {% else %}
                      {{field.label}}
                      {% endif %}
                    </h5>
                  </div>
                  <div class="card-body">
                    {{field}}
                  </div>
                  {% endfor %}
                </div>
                <button type='submit' class="btn btn-primary btn-lg">Kaydet</button>

      </form>
    </div>


  </div>
</div>

{% endblock %}

backsite/templates/backsite/create_about.html
{% extends 'backsite/main.html' %}
{% load static %}
{% block js%}
<script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
<script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
{% endblock %}


{% block body %}
<div class="container-fluid p-0">
  <div class='row'>
    <div class="col-md-8">
      <form method="post">
        {% csrf_token %}
        <div class="card">

                  <div class="card-header">
                    <h5 class="card-title mb-0">{{form.content.label}}</h5>
                  </div>
                  <div class="card-body">
                    {{form.content}}
                  </div>
                  </div>
                <button type='submit' class="btn btn-primary btn-lg">Kaydet</button>

      </form>
    </div>


  </div>
</div>

{% endblock %}

backsite/templates/backsite/index.html
{% extends 'backsite/main.html' %}
{% load static %}


{% block body %}
<div class="container-fluid p-0">
 <div class="row">
   <div class="col-md-2">
     <div class="card">
											<div class="card-body">
												<div class="row">
													<div class="col mt-0">
														<h5 class="card-title">Aktif Yazılar</h5>
													</div>

													<div class="col-auto">
														<div class="stat text-primary">
															<i class="align-middle" data-feather="book-open"></i>
														</div>
													</div>
												</div>
												<h1 class="mt-1 mb-3">{{active_blogs}}</h1>
											</div>
										</div>
   </div>
   <div class="col-md-2">
     <div class="card">
											<div class="card-body">
												<div class="row">
													<div class="col mt-0">
														<h5 class="card-title">Bütün Yazılar</h5>
													</div>

													<div class="col-auto">
														<div class="stat text-primary">
															<i class="align-middle" data-feather="layers"></i>
														</div>
													</div>
												</div>
												<h1 class="mt-1 mb-3">{{total_blogs}}</h1>
											</div>
										</div>
   </div>

   <div class="col-md-2">
     <div class="card">
											<div class="card-body">
												<div class="row">
													<div class="col mt-0">
														<h5 class="card-title">Aktif Kediler</h5>
													</div>

													<div class="col-auto">
														<div class="stat text-primary">
															<i class="align-middle" data-feather="book-open"></i>
														</div>
													</div>
												</div>
												<h1 class="mt-1 mb-3">{{active_cats}}</h1>
											</div>
										</div>
   </div>

   <div class="col-md-2">
     <div class="card">
											<div class="card-body">
												<div class="row">
													<div class="col mt-0">
														<h5 class="card-title">Bütün Kediler</h5>
													</div>

													<div class="col-auto">
														<div class="stat text-primary">
															<i class="align-middle" data-feather="layers"></i>
														</div>
													</div>
												</div>
												<h1 class="mt-1 mb-3">{{total_cats}}</h1>
											</div>
										</div>
   </div>

 </div>

</div>
{% endblock %}

backsite/templates/backsite/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="Honey Valerian Admin">
	<meta name="author" content="Honey Valerian Admin">



	<title>Honey Valerian Admin</title>

	<link href="{% static 'css/app.css' %}" rel="stylesheet">
	<link href="{% static 'css/style.css' %}" rel="stylesheet">
	<link href="{% static 'css/toastr.css' %}" rel="stylesheet">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css">
	<link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600&display=swap" rel="stylesheet">
	<script type="text/javascript" src="{% static 'js/jquery.min.js' %}">
	</script>
	<script type="text/javascript" src="{% static 'js/toastr.js' %}"></script>


  {% block css %}
  {% endblock %}
	{% block js %}
  {% endblock %}
</head>

<body>
	<div class="wrapper">
		<nav id="sidebar" class="sidebar js-sidebar">
			<div class="sidebar-content js-simplebar">
				<a class="sidebar-brand" href="{% url 'backsite:dashboard' %}">
          <span class="align-middle">Honey Valerian Cattery</span>
        </a>

				<ul class="sidebar-nav">
					<li class="sidebar-header">
						Pages
					</li>

					<li class="sidebar-item active">
						<a class="sidebar-link" href="{% url 'backsite:dashboard' %}">
              <i class="align-middle" data-feather="sliders"></i> <span class="align-middle">Dashboard</span>
            </a>
					</li>

					<li class="sidebar-item">
						<a class="sidebar-link" href="{% url 'backsite:my_cats' %}">
              <i class="align-middle" data-feather="heart"></i> <span class="align-middle">Kedilerim</span>
            </a>
					</li>

					<li class="sidebar-item">
						<a class="sidebar-link" href="{% url 'backsite:blogs' %}">
              <i class="align-middle" data-feather="book-open"></i> <span class="align-middle">Blog</span>
            </a>
					</li>

					<li class="sidebar-item">
						<a class="sidebar-link" href="{% url 'backsite:settings_func' %}">
              <i class="align-middle" data-feather="settings"></i> <span class="align-middle">Ayarlar</span>
            </a>
					</li>


				</ul>
			</div>
		</nav>

		<div class="main">
			<nav class="navbar navbar-expand navbar-light navbar-bg">
				<a class="sidebar-toggle js-sidebar-toggle">
          <i class="hamburger align-self-center"></i>
        </a>

				<div class="navbar-collapse collapse">
					<ul class="navbar-nav navbar-align">

						<li class="nav-item dropdown">
							<a class="nav-icon dropdown-toggle d-inline-block d-sm-none" href="#" data-bs-toggle="dropdown">
                <i class="align-middle" data-feather="settings"></i>
              </a>

							<a class="nav-link dropdown-toggle d-none d-sm-inline-block" href="{% url 'backsite:logoutpage' %}">
                <span class="text-dark">Çıkış Yap</span>
              </a>

						</li>
					</ul>
				</div>
			</nav>
 <!-- tepedeki navbar -->
			<main class="content">
			     {% block body %}
           {% endblock %}
			</main>
<!-- footer alanı -->

		</div>
	</div>

	<script src="{% static 'js/app.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery-3.6.1.min.js' %}">

	</script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


</body>

</html>

backsite/templates/backsite/my_cats.html
{% extends 'backsite/main.html' %}
{% load static %}


{% block body %}
<div class="container-fluid p-0">

        <h1 class="h3 mb-3">Kedi Ekleme Düzenleme Sayfası <a href="{% url 'backsite:create_cat' %}" class="btn btn-primary btn-lg" style="float:right">Kedi Ekle</a></h1>
  <div class="row">
      {% for cat in cats %}
      <div class="col-12 col-md-3">
            <div class="card">
              <img class="card-img-top" src="{{cat.img.url}}" style="max-width: 44%;margin: 0 auto;">
              <div class="card-header">
                <h5 class="card-title mb-0">{{cat.title}}</h5>
              </div>
              <div class="card-body">
                <p class="card-text">{{cat.content|safe|truncatechars:11}}</p>
                <a href="{% url 'backsite:update_cat' id=cat.id %}" class="btn btn-success"><i style="vertical-align: text-top!important;" data-feather="edit"></i> Düzenle</a>
                <a href="{% url 'backsite:delete_cat' id=cat.id %}" class="btn btn-danger"><i style="vertical-align: text-top!important;" data-feather="delete"></i> Sil</a>
              </div>
            </div>
          </div>

      {% endfor %}

  </div>

</div>
{% endblock %}

backsite/templates/backsite/settings.html
{% extends 'backsite/main.html' %}
{% load static %}
{% block js %}
<script type="text/javascript">
  $(document).ready(function(){
    $('#save_type').click(function(e){
      e.preventDefault();
      let cat_type=$('#cat_type').val();
      let cat_type_id=$('#cat_type_id').val();
      let url='{% url "backsite:cat_type_ajax" %}';
      $.ajax({
        url:url,
        method:'POST',
        data:{cat_type:cat_type,cat_type_id:cat_type_id,
        'csrfmiddlewaretoken': '{{ csrf_token }}'},
        success:function(res){
          console.log(res);
          if(res.success){
            toastr.success(res.msg);
            setTimeout(function() {
              location.reload();
            }, 2000);
          }else{
            toastr.error(res.msg);
          }


        }
      });
    });

    $('[id^="del_type_"]').click(function(){
      let id=$(this).attr('id').split('del_type_')[1];
      let url='{% url "backsite:del_cat_type_ajax" %}';
      $.ajax({
        url:url,
        method:'get',
        data:{id:id},
        success:function(res){
          console.log(res);
          if(res.success){
            toastr.success(res.msg);
            setTimeout(function() {
              location.reload();
            }, 2000);
          }else{
            toastr.error(res.msg);
          }
        }
      })
    })

    $('[id^="edit_type_"]').click(function(){
      let id=$(this).attr('id').split('edit_type_')[1];
      let url='{% url "backsite:edit_cat_type_ajax" %}';
      $.ajax({
        url:url,
        method:'get',
        data:{id:id},
        success:function(res){
          console.log(res);
          if(res.success){
            $('#cat_type').val(res.title);
            $('#cat_type_id').val(res.id);
            $('#cat_add_modal').addClass('show');
          }else{
            toastr.error(res.msg);
          }
        }
      })
    })



  });

</script>

{% endblock %}

{% block body %}
<div class="container-fluid p-0">

        <h1 class="h3 mb-3">Ayarlar</h1>
  <div class="row">
      <div class="col-12 col-md-3">
        {% if about %}
        <a href="{% url 'backsite:update_about' id=about.id %}" class="btn btn-primary btn-lg">Hakkımınzda Yazısı Düzenle</a>

            {% else %}
            <a href="{% url 'backsite:create_about' %}" class="btn btn-primary btn-lg">Hakkımınzda Yazısı Ekle</a>

          {% endif %}
        </div>
        <div class='col-md-12' style="margin-top:1%;">
          <h2>Kedi Türleri<button id='cat_modal_button' type="button" class="btn btn-primary btn-lg" style='float:right;' data-bs-toggle="modal" data-bs-target="#cat_add_modal"">Kedi Türü Ekle</button></h2>
          <div class="cat_types" style='padding:1%'>
            {% for type in cat_types %}
            <span class="type_span">{{ type.title }} <button class='type_del_button' type="button" id="edit_type_{{ type.id }}" ><i class="fa fa-edit" aria-hidden="true"></i></button><button class='type_del_button' type="button" id="del_type_{{ type.id }}" ><i class="fa fa-times" aria-hidden="true"></i></button></span>
            {% endfor %}

          </div>
        </div>


  </div>
<!-- kedi türü ekleme modal -->

</div>

  <div class="modal fade bg" style="margin-top:2%;" id="cat_add_modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Kedi Türü Ekle<button type="button" class="btn-close" style="float:right;" data-bs-dismiss="modal" aria-label="Close"></button></h5>

      </div>
      <div class="modal-body">
        <div class="col-sm-12">
          <form id='cat_form' method="post">
            {% csrf_token %}
            <input type="text" class="form-control" id="cat_type" name='cat_type'>
            <input type="hidden" class="form-control" id="cat_type_id" name='cat_type_id'>
          </form>
      </div>
      </div>
      <div class="modal-footer" style='margin-top:1%;'>
        <button type="button" id='save_type'style="float:right;" class="btn btn-primary">Kaydet</button>
      </div>
    </div>
  </div>


</div>


{% endblock %}