cattery/urls.py
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from frontsite.views import index,about,contact_func,cats_blog,cat_info
from core.views import error_404_view
from django.conf.urls import (
handler400, handler403, handler404, handler500
)

urlpatterns = [
    path('',index,name='index'),
    path('about/',about,name='about'),
    path('contact_us/',contact_func,name='contact_us'),
    path('valerian_admin/',include('backsite.urls',namespace='panel')),
    path('blog/',include('frontsite.urls',namespace='front')),
    path('our_cats/',cats_blog,name='cats_blog'),
    path('our_cats/<int:id>',cat_info,name='cat_info'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

handler404 = 'core.views.error_404_view'
handler500 = 'core.views.error_500_view'

frontsite/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import *

app_name='frontsite'
urlpatterns = [
    path('',blogs,name='blogs'),
    path('<str:slug>/',blog_page,name='blog_page'),


]

templates/about_us.html
{% extends 'main.html' %}
{% load static %}

{% block body %}
<section class="astroid-section" id="ts-451555907311432"><div class="container"><div class="astroid-row row" id="ar-701555907311432"><div class="astroid-column col-lg-12 order-xl-0 order-lg-0 order-md-0 order-sm-0 order-0" id="ac-651555907311432"><div class="astroid-module-position" id="bp-731555907356229"> <div class="moduletable ">
         <div aria-label="breadcrumbs" role="navigation" class="mod_breadcrumbs">
	    <h2 class="heading-title-page">Hakkımızda</h2>
	<!-- <ul itemscope="" itemtype="https://schema.org/BreadcrumbList" class="breadcrumb uk-breadcrumb">
		            <li>
				You are here: &nbsp;
            </li>
								<li itemprop="itemListElement" itemscope="" itemtype="https://schema.org/ListItem">
											<a itemprop="item" href="/index.php/en/" class="pathway"><span itemprop="name">Home</span></a>
										<meta itemprop="position" content="1">
				</li>
							<li itemprop="itemListElement" itemscope="" itemtype="https://schema.org/ListItem">
											<a itemprop="item" href="/index.php/en/blog" class="pathway"><span itemprop="name">Blog</span></a>
										<meta itemprop="position" content="2">
				</li>
							<li itemprop="itemListElement" itemscope="" itemtype="https://schema.org/ListItem" class="active">
					<span itemprop="name">
						7 Reasons to Walk Your Dog					</span>
					<meta itemprop="position" content="3">
				</li>
				</ul> -->
</div> </div> </div></div></div></div></section>
<section class="astroid-section astroid-component-section" id="cs-1528971561366"><div class="container"><div class="astroid-row row" id="ar-1528971561366"><div class="astroid-column col-md-12" id="ac-511555906566780"><div class="astroid-message" id="am-711555907090073"><div id="system-message-container">
   </div></div><div class="astroid-component" id="ca-1121555907157112"><main class="astroid-component-area">
   <div class="item-page" itemscope="" itemtype="https://schema.org/Article">
   <meta itemprop="inLanguage" content="en">



		       <div class="item-detail-container">



<div itemprop="articleBody" class="article-body">
  {{about.content|safe}}
</div>
</div>




</div> </div> </div></div></div></div></section>
{% endblock %}

templates/blog-page.html
{% extends 'main.html' %}
{% load static %}

{% block body %}
<section class="astroid-section" id="ts-451555907311432"><div class="container"><div class="astroid-row row" id="ar-701555907311432"><div class="astroid-column col-lg-12 order-xl-0 order-lg-0 order-md-0 order-sm-0 order-0" id="ac-651555907311432"><div class="astroid-module-position" id="bp-731555907356229"> <div class="moduletable ">
         <div aria-label="breadcrumbs" role="navigation" class="mod_breadcrumbs">
	    <h2 class="heading-title-page">{{blog.title}}</h2>
	<!-- <ul itemscope="" itemtype="https://schema.org/BreadcrumbList" class="breadcrumb uk-breadcrumb">
		            <li>
				You are here: &nbsp;
            </li>
								<li itemprop="itemListElement" itemscope="" itemtype="https://schema.org/ListItem">
											<a itemprop="item" href="/index.php/en/" class="pathway"><span itemprop="name">Home</span></a>
										<meta itemprop="position" content="1">
				</li>
							<li itemprop="itemListElement" itemscope="" itemtype="https://schema.org/ListItem">
											<a itemprop="item" href="/index.php/en/blog" class="pathway"><span itemprop="name">Blog</span></a>
										<meta itemprop="position" content="2">
				</li>
							<li itemprop="itemListElement" itemscope="" itemtype="https://schema.org/ListItem" class="active">
					<span itemprop="name">
						7 Reasons to Walk Your Dog					</span>
					<meta itemprop="position" content="3">
				</li>
				</ul> -->
</div> </div> </div></div></div></div></section>
<section class="astroid-section astroid-component-section" id="cs-1528971561366"><div class="container"><div class="astroid-row row" id="ar-1528971561366"><div class="astroid-column col-lg-6 order-xl-0 order-lg-0 order-md-0 order-sm-0 order-0 col-lg-9" id="ac-511555906566780"><div class="astroid-message" id="am-711555907090073"><div id="system-message-container">
   </div></div><div class="astroid-component" id="ca-1121555907157112"><main class="astroid-component-area">
   <div class="item-page" itemscope="" itemtype="https://schema.org/Article">
   <meta itemprop="inLanguage" content="en">



		<div class="entry-image full-image mb-3"> <img style="width: fit-content;height: 418px;"src="{{blog.img.url}}" alt="" itemprop="image" class="img-fluid"> </div>
                    <dl class="article-info muted">



               	<dd class="published">
		<i class="far fa-calendar-check"></i>
		<time datetime="2020-08-25T07:01:10+00:00" itemprop="datePublished">{{blog.created_at}}</time>
	</dd>
</dl>        <div class="item-detail-container">



<div itemprop="articleBody" class="article-body">
  {{blog.content|safe}}
</div>
</div>




</div> </div> </div></div></div></div></section>
{% endblock %}

templates/blogs.html
{% extends 'main.html' %}
{% load static %}
{% block css %}
<style media="screen">
	.contentP{
		bottom: 7%;
right: -15%;
position: absolute;
background: #c88948;
color: white;
width: 91%;
font-size: x-large;
padding: 2%;
	}
</style>
{% endblock %}
{% block body %}
<section class="astroid-section" id="ts-451555907311432"><div class="container"><div class="astroid-row row" id="ar-701555907311432">
	    <h2 class="heading-title-page">Blog Yazıları</h2>

      <div class="astroid-column col-lg-6 order-xl-0 order-lg-0 order-md-0 order-sm-0 order-0 col-lg-9" id="ac-511555906566780">
        <div data-blog-listings="" class="DS07740006468937992">
          {% for blog in blogs %}
          <div class="eb-post" style="border-bottom: 3px solid #c88948;
    padding: 1%;position:relative;">
  <div class="eb-post-content">

          <div class="eb-post-avatar t-lg-pull-left t-mr--md">
      <div class="o-avatar  ">
<div class="o-avatar__mobile"></div>


</div>			</div>

    <div class="eb-post-head no-overflow">
                <h2 class="eb-post-title reset-heading ">
<div href="#" class="text-inherit">{{blog.title}}</div>
</h2>

                <div class="eb-post-meta text-muted">

  <div>
  <div class="eb-post-date">

<time class="eb-meta-date ddate">
  Eklenme Tarihi: {{blog.created_at|date:"d-m-Y"}}</time>
</div>
</div>

  <div>
  <div class="eb-post-author">

<span>

</span>
</div>
</div>

  <div>
  <div class="eb-post-category comma-seperator">

  <span>
</span>
</div>	</div>


</div>
            </div>

            <div class="eb-post-body type-standard" data-blog-post-content="">
    <div class="eb-post-thumb is-full">
    <div class="eb-post-image" style="
              width: 100%;
              ">
                      <img src="{{blog.img.url}}" alt="ludemeula-fernandes-9UUoGaaHtNE-unsplas_20210303-084920_1">

        </div>
</div>
<div class="contentP">
	{{blog.content|safe|truncatewords:15}}
	<a href="{% url 'frontsite:blog_page' slug=blog.url %}" style='float: right;color:white;margin-top: 2%;'>
Devamını Oku</a>
</div>
</div>


              <div class="eb-post-more mt-20">

      </div>







        </div>


  <script type="application/ld+json">
{
"@context": "http://schema.org",
"mainEntityOfPage": "https://pethub.jollyany.co/index.php/en/blog/easyblog/5-cleaning-hacks-to-beat-pet-allergies",
"@type": "BlogPosting",
"headline": "5 Cleaning Hacks to Beat Pet Allergies",
"image": "https://pethub.jollyany.co/images/easyblog_articles/10/b2ap3_large_ludemeula-fernandes-9UUoGaaHtNE-unsplas_20210303-084920_1.jpg",
"editor": "Victoria Rawson",
"genre": "Blogs",
"publisher": {
  "@type": "Organization",
  "name": "PetHub",
  "logo": {"@type":"ImageObject","url":"https:\/\/pethub.jollyany.co\/media\/com_easyblog\/images\/schema\/logo.png","width":60,"height":60}	},
"datePublished": "2021-02-19",
"dateCreated": "2021-02-19",
"dateModified": "2021-03-03",
"description": "",
"author": {
  "@type": "Person",
  "url": "https://pethub.jollyany.co/index.php/en/blog/easyblog/blogger/admin",
  "name": "Victoria Rawson",
  "image": "https://pethub.jollyany.co/images/easyblog_avatar/777_03_testimonial.jpg"
}
}
</script>
</div>
          {% endfor %}


        </div>

      </div>

      </div>


      </section>
{% endblock %}

templates/cat_info.html
{% extends 'main.html' %}
{% load static %}

{% block body %}
  <div class="container">
    <div class="row">
      <div class="col-md-8">
        <div data-eb-posts="" class="DS022717362007472075">
        	<div data-eb-posts-wrapper="">
        		<div data-eb-post-section="" data-url="https://pethub.jollyany.co/index.php/en/blog/easyblog/5-cleaning-hacks-to-beat-pet-allergies" data-page-title="PetHub - Blog - 5 Cleaning Hacks to Beat Pet Allergies" data-permalink="/index.php/en/blog/easyblog/5-cleaning-hacks-to-beat-pet-allergies" data-post-title="5 Cleaning Hacks to Beat Pet Allergies">
        	<div class="eb-adsense-head clearfix">
        			</div>

        	<div data-blog-post="" class="DS07351681330187949">


        		<div id="entry-10" class="eb-entry fd-cf" data-blog-posts-item="" data-id="10" data-uid="10.27">

        			<div data-blog-reading-container="">

        				<div class="eb-entry-head">
        											<h1 id="title-10" class="eb-entry-title reset-heading  ">
        	{{cat.title}}</h1>

        		<div class="eb-post-date">

        	<time class="eb-meta-date" content="2021-02-19">
        		Eklenme Tarihi - {{cat.created_at|date:"d-m-Y"}}</time>

        </div>
        	</div>

        	</div>
        				</div>

        				<div class="eb-entry-body type-standard clearfix">
        					<div class="eb-entry-article clearfix" data-blog-content="">


        						<div class="eb-image eb-post-thumb is-full" data-eb-entry-cover="">
                      <div class="gender-type">

                        <span style="position: absolute;color:white;
    padding: 10px 20px;background:{% if cat.gender == 1 %}pink;{% else %}blue;{% endif %}">{% if cat.gender == 1 %}Dişi{% else %}Erkek{% endif %} - {{cat.cat_type.title}}</span>
                      </div>
        			<a class="eb-post-image eb-image-popup-button" href="//pethub.jollyany.co/images/easyblog_articles/10/ludemeula-fernandes-9UUoGaaHtNE-unsplas_20210303-084920_1.jpg" target="_blank" title="ludemeula-fernandes-9UUoGaaHtNE-unsplas_20210303-084920_1" caption="" style="
        								width: 100%;
        				">
        												<img src="{{cat.img.url}}" alt="ludemeula-fernandes-9UUoGaaHtNE-unsplas_20210303-084920_1">


        					</a>

        	</div>

        <div class="ebd-block   " data-type="text">
          {{cat.content|safe}}
        </div>




        											</div>








        										<div class="eb-entry-tags">
        											</div>





        									</div>
        			</div>



        												</div>





        <a class="eb-anchor-link" name="comments" id="comments" data-allow-comment="1">&nbsp;</a>

         			</div>

        	<div class="eb-adsense-foot clearfix">
        			</div>
        </div>

        <script type="application/ld+json">
        {
        	"@context": "http://schema.org",
        	"mainEntityOfPage": "https://pethub.jollyany.co/index.php/en/blog/easyblog/5-cleaning-hacks-to-beat-pet-allergies",
        	"@type": ["BlogPosting", "Organization"],
        	"name": "PetHub",
        	"headline": "5 Cleaning Hacks to Beat Pet Allergies",
        	"image": "https://pethub.jollyany.co/images/easyblog_articles/10/b2ap3_large_ludemeula-fernandes-9UUoGaaHtNE-unsplas_20210303-084920_1.jpg",
        	"editor": "Victoria Rawson",
        	"genre": "Blogs",
        	"wordcount": "468",
        	"publisher": {
        		"@type": "Organization",
        		"name": "PetHub",
        		"logo": {"@type":"ImageObject","url":"https:\/\/pethub.jollyany.co\/media\/com_easyblog\/images\/schema\/logo.png","width":60,"height":60}	},
        	"datePublished": "2021-02-19",
        	"dateCreated": "2021-02-19",
        	"dateModified": "2021-03-03",
        	"description": "",
        	"articleBody": "&lt;div  class=&quot;ebd-block   &quot; data-type=&quot;text&quot; &gt;&lt;p&gt;Pet allergies are unpleasant.&amp;nbsp;Itchy eyes, sneezing, a runny nose, and wheezing can all make living with a dog very difficult. If you&#039;ve made the decision to bring a dog into your home, or if you have family and friends who are allergic to your dog, there are plenty of ways to reduce the number of allergens in your home. These hacks will help manage pet allergies and make life more pleasant.&lt;br&gt;&lt;/p&gt;&lt;/div&gt;
        &lt;div  class=&quot;ebd-block   &quot; data-type=&quot;text&quot; &gt;&lt;p&gt;Most people think they are allergic to pet hair; however, allergies are usually a reaction to the proteins in their dander (dead skin), urine and saliva. If you knew you had an allergy before you bought a dog, hopefully you chose a hypoallergenic dog which is less likely to trigger reactions because they produce less dander.&lt;/p&gt;&lt;/div&gt;
        &lt;div  class=&quot;ebd-block   &quot; data-type=&quot;heading&quot; &gt;&lt;h3&gt;Hack #1: Have Some Dog-Free Areas&lt;/h3&gt;&lt;/div&gt;
        &lt;div  class=&quot;ebd-block   &quot; data-type=&quot;image&quot; style=&quot;text-align: center;&quot;&gt;&lt;div class=&quot;eb-image style-clear&quot;&gt;
        	&lt;div class=&quot;eb-image-figure is-responsive&quot;&gt;

        					&lt;a class=&quot;eb-image-viewport&quot;&gt;
        									&lt;img src=&quot;images/easyblog_articles/10/b2ap3_large_krista-mangulsone-9gz3wfHr65U-unsplash.jpg&quot; 				/&gt;
        									&lt;/a&gt;
        	&lt;/div&gt;
        				&lt;/div&gt;&lt;/div&gt;
        &lt;div  class=&quot;ebd-block   &quot; data-type=&quot;text&quot; &gt;&lt;p&gt;Consider having a few rooms which your dog isn&#039;t allowed into. Don&#039;t allow your dog into your bedroom or on your bed, and consider keeping him off furniture which you frequently use, such as your sofa. This won&#039;t stop pet allergens spreading to these areas, but it will reduce the amount of dander.&lt;/p&gt;&lt;/div&gt;
        &lt;div  class=&quot;ebd-block   &quot; data-type=&quot;heading&quot; &gt;&lt;h3&gt;Hack #2: Say Goodbye to Carpets&lt;/h3&gt;&lt;/div&gt;
        &lt;div  class=&quot;ebd-block   &quot; data-type=&quot;text&quot; &gt;&lt;p&gt;Carpets can trap dog hair and dander making it difficult to remove even after a good vacuuming. Stick to hard surface flooring such as wood, vinyl laminate or tile. These surfaces are much easier to keep clean and hair &amp;amp; dander free. Vacuuming and mopping removes pet allergens quite quickly.&lt;br&gt;&lt;br&gt;If you are set on having carpets, choose a low pile which is less likely to trap allergens. Please keep in mind that you should have them professionally cleaned frequently.&lt;br&gt;&lt;/p&gt;&lt;/div&gt;
        &lt;div  class=&quot;ebd-block   &quot; data-type=&quot;heading&quot; &gt;&lt;h3&gt;Hack #3: Bathe and Brush Regularly&lt;/h3&gt;&lt;/div&gt;
        &lt;div  class=&quot;ebd-block   &quot; data-type=&quot;text&quot; &gt;&lt;p&gt;If you have a visitor coming over who is allergic to your four-legged friend, you might want to consider giving your pooch the ultimate spa treatment to reduce the number of allergens. Unfortunately, this isn&#039;t a great long-term solution for those living with the dog. It is only a temporary fix since allergens will be back in two to three days after the bath.&lt;/p&gt;&lt;/div&gt;
        &lt;div  class=&quot;ebd-block   &quot; data-type=&quot;heading&quot; &gt;&lt;h3&gt;Hack #4: Use an Air Purifier&lt;/h3&gt;&lt;/div&gt;
        &lt;div  class=&quot;ebd-block   &quot; data-type=&quot;text&quot; &gt;&lt;p&gt;Using an air purifier with a HEPA filter can remove impurities and pet allergens from the air. These purifiers work by trapping particles which cause allergic reactions so it&#039;s important that you use it in the rooms that your dog uses the most.&lt;/p&gt;&lt;/div&gt;
        &lt;div  class=&quot;ebd-block   &quot; data-type=&quot;heading&quot; &gt;&lt;h3&gt;Hack #5: Clean and Dust Regularly&lt;/h3&gt;&lt;/div&gt;
        &lt;div  class=&quot;ebd-block   &quot; data-type=&quot;text&quot; &gt;&lt;p&gt;Having a cleaning schedule in place will help to prevent allergens from building up. Invest in a pet vacuum which has been specifically developed to help remove hair, dander and pet odors. Dusting regularly will also help to keep dander levels to a minimum. Make sure you clean and dust all the areas which your dog regularly uses, as well as their toys and bed.&lt;/p&gt;&lt;/div&gt;
        ",
        	"author": {
        		"@type": "Person",
        		"url": "https://pethub.jollyany.co/index.php/en/blog/easyblog/blogger/admin",
        		"name": "Victoria Rawson",
        		"image": "https://pethub.jollyany.co/images/easyblog_avatar/777_03_testimonial.jpg"
        	}}
        </script>

        	</div>

        	</div>



      </div>

    </div>
  </div>
{% endblock %}

templates/navbar.html
{% load static %}

<section class="astroid-section astroid-header-section" id="hs-1529472563843">
    <div class="container">
        <div class="astroid-row row" id="ar-1529472563843">
            <div class="astroid-column col-lg-12 order-xl-0 order-lg-0 order-md-0 order-sm-0 order-0" id="ac-1529472563843">
                <div class="astroid-module-position" id="jh-1529472563843">
                    <!-- header starts -->
                    <header data-megamenu="" data-megamenu-class=".has-megamenu" data-megamenu-content-class=".megamenu-container" data-dropdown-arrow="true" data-header-offset="true" data-transition-speed="100" data-megamenu-animation="slide" data-easing="linear" data-astroid-trigger="hover"
                        data-megamenu-submenu-class=".nav-submenu,.nav-submenu-static" id="astroid-header" class="astroid-header astroid-horizontal-header astroid-horizontal-center-header">
                        <div class="d-flex flex-row justify-content-between">
                            <div class="d-flex d-lg-none justify-content-start">
                                <div class="header-mobilemenu-trigger d-lg-none burger-menu-button align-self-center" data-offcanvas="#astroid-mobilemenu" data-effect="mobilemenu-slide">
                                    <button aria-label="Mobile Menu Toggle" class="button" id="mobileButton" onclick="mobileButton()" type="button"><span class="box"><span class="inner"></span></span></button>
                                </div>
                            </div>
                            <div class="header-left-section d-flex justify-content-start">
                                <!-- logo starts -->
                                <!-- image logo starts -->
                                <div class="logo-wrapper astroid-logo">
                                    <a target="_self" class="astroid-logo astroid-logo-image d-flex align-items-center mr-0 mr-lg-4" href="{% url 'index' %}">
                                        <img src="{% static 'img/yeniweblogo.png'%}" alt="PetHub" class="astroid-logo-default">
                                        <img src="https://pethub.jollyany.co/images/tz_pethub/logo.png" alt="PetHub" class="astroid-logo-mobile">
                                        <img src="https://pethub.jollyany.co/images/tz_pethub/logo_sticky.png" alt="PetHub" class="astroid-logo-sticky">
                                    </a>
                                </div>
                                <!-- image logo ends -->
                                <!-- logo ends -->
                            </div>
                            <div class="header-center-section d-none d-lg-flex justify-content-center flex-lg-grow-1">
                                <div class=" align-self-center px-2 d-none d-lg-block">
                                    <ul class="nav astroid-nav d-none d-lg-flex">
                                        <li data-position="right" class="nav-item-submenu nav-item-id-325 nav-item-level-2">
                                            <!--menu link starts-->
                                            <a href="{% url 'about' %}" title="Hakkımızda" class="  nav-link-item-id-105 nav-link item-link-component item-level-1" data-drop-action="hover">
                                                <span class="nav-title">
                                          Hakkımızda                              </span>
                                            </a>
                                            <!--menu link ends-->
                                        </li>
                                        <li data-position="right" class="nav-item nav-item-id-105 nav-item-level-1">
                                            <!--menu link starts-->
                                            <a href="{% url 'cats_blog' %}" title="Courses" class=" nav-link-item-id-105 nav-link item-link-component item-level-1" data-drop-action="hover">
                                                <span class="nav-title">
                                          Kedilerimiz                            </span>
                                            </a>
                                            <!--menu link ends-->
                                        </li>
                                        <li data-position="right" class="nav-item nav-item-id-105 nav-item-level-1">
                                            <!--menu link starts-->
                                            <a href="{% url 'frontsite:blogs' %}" title="Blog" class=" nav-link-item-id-105 nav-link item-link-component item-level-1" data-drop-action="hover">
                                                <span class="nav-title">
                                          Blog
                  </span>
                                            </a>
                                            <!--menu link ends-->
                                        </li>
                                        <li data-position="right" class="nav-item nav-item-id-295 nav-item-level-1">
                                            <!--menu link starts-->
                                            <a href="{% url 'contact_us' %}" title="Shop" class=" nav-link-item-id-295 nav-link item-link-component item-level-1" data-drop-action="hover">
                                                <span class="nav-title">İletişim</span>
                                            </a>
                                            <!--menu link ends-->
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div class="header-right-section d-flex justify-content-end">
                                <div class="header-right-block d-none d-lg-block align-self-center mx-4">
                                    <div class="header-block-item d-flex justify-content-end align-items-center"></div>
                                </div>
                                <div class="header-offcanvas-trigger burger-menu-button align-self-center d-block" data-offcanvas="#astroid-offcanvas" data-effect="st-effect-2" data-direction="offcanvasDirLeft">

                                </div>
                            </div>
                        </div>
                        <div class="astroid-mobilemenu d-init dir-left mobilemenu-slide" data-class-prefix="astroid-mobilemenu" id="astroid-mobilemenu">
                            <div class="burger-menu-button active">
                                <button aria-label="Mobile Menu Toggle" id="menuClose" onclick='menuClose()' type="button" class="button close-offcanvas offcanvas-close-btn">
                  <span class="box">
                     <span class="inner"></span>
                  </span>
               </button>
                            </div>
                            <div class="astroid-mobilemenu-container">
                                <div class="astroid-mobilemenu-inner">
                                    <ul class="astroid-mobile-menu">
                                        <li class="nav-item nav-item-id-105 nav-item-level-1 menu-item">
                                            <!--menu link starts-->
                                            <a href="{% url 'about' %}" title="Hakkımızda" class=" nav-link-item-id-105 nav-link item-link-component item-level-1" data-drop-action="hover">
                                                <span class="nav-title">
                                                        Hakkımızda                              </span>
                                            </a>
                                            <!--menu link ends-->
                                        </li>
                                        <li class="nav-item nav-item-id-105 nav-item-level-1 menu-item">
                                            <!--menu link starts-->
                                            <a href="{% url 'cats_blog' %}" title="Kedilerimiz" class=" nav-link-item-id-105 nav-link item-link-component item-level-1" data-drop-action="hover">
                                                <span class="nav-title">
                                                        Kedilerimiz                              </span>
                                            </a>
                                            <!--menu link ends-->
                                        </li>
                                        <li class="nav-item nav-item-id-105 nav-item-level-1 menu-item">
                                            <!--menu link starts-->
                                            <a href="{% url 'frontsite:blogs' %}" title="Blog" class=" nav-link-item-id-105 nav-link item-link-component item-level-1" data-drop-action="hover">
                                                <span class="nav-title">
                                                        Blog                              </span>
                                            </a>
                                            <!--menu link ends-->
                                        </li>
                                        <li class="nav-item nav-item-id-105 nav-item-level-1 menu-item">
                                            <!--menu link starts-->
                                            <a href="{% url 'contact_us' %}" title="İletişim" class=" nav-link-item-id-105 nav-link item-link-component item-level-1" data-drop-action="hover">
                                                <span class="nav-title">
                                                        İletişim                              </span>
                                            </a>
                                            <!--menu link ends-->
                                        </li>

                                    </ul>
                                </div>
                            </div>
                        </div>
                        <!-- header ends -->
                </div>
            </div>
        </div>
    </div>
</section>